# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CnvMeshToXYZ
                                 A QGIS plugin
 Converting mesh polygons to XYZ format
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-09-10
        copyright            : (C) 2021 by Y.Kayama/Aeroasahi Corporation
        email                : yoichi.kayama@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Y.Kayama/Aeroasahi Corporation'
__date__ = '2021-09-10'
__copyright__ = '(C) 2021 by Y.Kayama/Aeroasahi Corporation'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CnvMeshToXYZ class from file CnvMeshToXYZ.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .CnvMeshToXYZ import CnvMeshToXYZPlugin
    return CnvMeshToXYZPlugin()
